@server=http://localhost:4004
@username=integration
@password=1234


### IntegrationLogs
# @name IntegrationLogs_POST_SF
POST {{server}}/odata/v4/log-monitor-integration/IntegrationLogs
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "1265ac03-a1a3-4b0d-9dac-0ca70b478198",
  "integration_ID": "a1b2c3d4-0001-4000-8000-000000000001",
  "executedAt": "2005-11-10T00:00:00.000Z",
  "status": "ERROR",
  "payload": "{\"employeeId\":\"999\",\"costCenter\":\"001\",\"lastName\":\"Freitas\",\"firstName\":\"joao\",\"jobTitle\":\"developer\"}"
}
