@server=http://localhost:4004


### IntegrationLogs
# @name IntegrationLogs_GET
GET {{server}}/odata/v4/log-monitor/IntegrationLogs



### IntegrationLogs
# @name IntegrationLogs_POST
POST {{server}}/odata/v4/log-monitor/IntegrationLogs
Content-Type: application/json

{
  "ID": "16820079-b627-4813-9e78-0e48006034cf",
  "integration_ID": "d00b4a9e-d8ea-4d59-bb84-85cd9fc7f801",
  "executedAt": "2005-11-10T00:00:00.000Z",
  "status": "ERROR",
  "payload": "{\"employeeId\":\"999\",\"costCenter\":\"001\",\"lastName\":\"Freitas\",\"firstName\":\"joao\",\"jobTitle\":\"developer\"}",
  "createdAt": "2023-10-14T00:00:00.000Z",
  "createdBy": "createdBy.a0igf@example.com",
  "modifiedAt": "2001-03-20T00:00:00.000Z",
  "modifiedBy": "modifiedBy.a0igf@example.net"
}


### IntegrationLogs
# @name IntegrationLogs_DELETE
DELETE {{server}}/odata/v4/log-monitor/IntegrationLogs/16820079-b627-4813-9e78-0e48006034cf
Content-Type: application/json
