@server=http://localhost:4004
@username=john.doe@dummy.com
@password=1234


### IntegrationLogs
# @name IntegrationLogs_GET
GET {{server}}/odata/v4/log-monitor-cockpit/IntegrationLogs?$expand=integration($expand=userIntegrations($expand=user))
Authorization: Basic {{username}}:{{password}}



### IntegrationLogs
# @name IntegrationLogs_POST
POST {{server}}/odata/v4/log-monitor-cockpit/IntegrationLogs
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "16820079-b627-4813-9e78-0e48006034cf",
  "integration_ID": "a1b2c3d4-0001-4000-8000-000000000001",
  "executedAt": "2005-11-10T00:00:00.000Z",
  "status": "ERROR",
  "payload": "{\"employeeId\":\"999\",\"costCenter\":\"001\",\"lastName\":\"Freitas\",\"firstName\":\"joao\",\"jobTitle\":\"developer\"}"
}


### IntegrationLogs
# @name IntegrationLogs_POST_ARIBA
POST {{server}}/odata/v4/log-monitor-cockpit/IntegrationLogs
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "27931180-c738-4924-af89-1f59007145df",
  "integration_ID": "a1b2c3d4-0002-4000-8000-000000000002",
  "executedAt": "2026-09-21T00:00:00.000Z",
  "status": "ERROR",
  "payload": "{\"purchaseOrderId\":\"PO-4521\",\"supplierId\":\"SUP-100\",\"totalAmount\":15230.50,\"currency\":\"BRL\"}"
}


### IntegrationLogs
# @name IntegrationLogs_POST_CONCUR
POST {{server}}/odata/v4/log-monitor-cockpit/IntegrationLogs
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "38a42291-d849-4a35-b09a-2f6a018256e0",
  "integration_ID": "a1b2c3d4-0003-4000-8000-000000000003",
  "executedAt": "2026-09-21T00:00:00.000Z",
  "status": "ERROR",
  "payload": "{\"expenseReportId\":\"ER-7734\",\"employeeId\":\"E-2201\",\"totalAmount\":842.15,\"currency\":\"BRL\"}"
}


### IntegrationLogs
# @name IntegrationLogs_DELETE
DELETE {{server}}/odata/v4/log-monitor-cockpit/IntegrationLogs/16820079-b627-4813-9e78-0e48006034cf
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### IntegrationLogs
# @name IntegrationLogs_DELETE
DELETE {{server}}/odata/v4/log-monitor-cockpit/IntegrationLogs/27931180-c738-4924-af89-1f59007145df
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### IntegrationLogs
# @name IntegrationLogs_DELETE
DELETE {{server}}/odata/v4/log-monitor-cockpit/IntegrationLogs/38a42291-d849-4a35-b09a-2f6a018256e0
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}