@server=http://localhost:4004
@username=john.doe@dummy.com
@password=1234


### UserIntegrations
# @name UserIntegrations_GET
GET {{server}}/odata/v4/log-monitor-cockpit/UserIntegrations?$expand=user,integration
Authorization: Basic {{username}}:{{password}}


### UserIntegrations
# @name UserIntegrations_POST
POST {{server}}/odata/v4/log-monitor-cockpit/UserIntegrations
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "12860188-c5e9-46f4-b0ec-f2b624337162",
  "user": {
    "ID": "161033c5-c4e9-46d2-a669-161052b0a1f6"
  },
  "integration": {
    "ID": "a1b2c3d4-0001-4000-8000-000000000001"
  }
}


### UserIntegrations
# @name UserIntegrations_PATCH
PATCH {{server}}/odata/v4/log-monitor-cockpit/UserIntegrations/12860188-c5e9-46f4-b0ec-f2b624337162
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{}


### UserIntegrations
# @name UserIntegrations_DELETE
DELETE {{server}}/odata/v4/log-monitor-cockpit/UserIntegrations/12860188-c5e9-46f4-b0ec-f2b624337162
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}
